"""Tests for wasmjs.wasmjs."""

import pytest

from wasmjs import wasmjs


def test_basic():
    """Quick smoke test."""

    js = wasmjs.WasmJS()
    assert js.eval('1 + 2') == 3
    assert js.eval('"hello" + "there"') == 'hellothere'
    assert js.eval('function test(a, b) { return a * b; }; test(2, 3);') == 6
    assert js.eval('({hello: 5});') == {'hello': 5}

    with pytest.raises(wasmjs.JSError, check=lambda e: e.name == 'SyntaxError'):
        js.eval('1 +')

    # Stub values are hidden.
    with pytest.raises(wasmjs.JSError, check=lambda e: e.name == 'ReferenceError'):
        js.eval('next_generator_id')

    # Local variables are not persisted.
    assert js.eval('let test_basic_num = 1000; test_basic_num;') == 1000
    with pytest.raises(wasmjs.JSError, check=lambda e: e.name == 'ReferenceError'):
        js.eval('test_basic_num')


def test_protocol_poison():
    """Make sure things that look like how WasmJS transports generators don't confuse it."""

    js = wasmjs.WasmJS()

    assert js.eval("({'#': 1000, blah: 2000});") == {'#': 1000, 'blah': 2000}
    assert js.eval("({'#': {'value': 1000}, blah: 2000});") == {'#': {'value': 1000}, 'blah': 2000}
    assert js.eval("({'#': {type: 'Generator', id: 1000}});") == {
        '#': {
            'type': 'Generator',
            'id': 1000,
        },
    }


def test_internal_errors():
    """Document known traps generated by qjs."""

    # See https://github.com/quickjs-ng/quickjs/issues/1460.
    js = wasmjs.WasmJS()

    with pytest.raises(wasmjs.JSError):
        js.eval("JSON.parse('['.repeat(2940));")

    with pytest.raises(wasmjs.InterpreterError):
        js.eval("JSON.parse('['.repeat(2941));")
