"""Simple wrapper around QuickJS-NG's qjs-wasi-reactor.wasm."""

import importlib.resources
import json

from wasmjs import wasmfile


class WasmJS:
    """Simple wrapper around QuickJS-NG's qjs-wasi-reactor.wasm."""

    _wasmfile = None

    def __init__(self):
        if not self._wasmfile:
            WasmJS._wasmfile = wasmfile.WasmFile(wasm=importlib.resources.files(
                'qjs-wasi-reactor').joinpath('qjs-wasi-reactor.wasm').read_bytes())

        self._inst = self._wasmfile.instantiate()
        assert self._inst.exports.memory.pointer_size == 4, (
            'This build of wasmjs assumes JSValues are NaN-boxed int64s.')

        if self._bootstrap:
            with self._inst.api.js.eval_to_jsval(self._bootstrap):
                pass

    _bootstrap = """
      {
        let generators = new Map();
        let next_generator_id = 0;

        function wrap(fn, ...args) {
          let value;
          try {
            value = fn(...args);
          } catch (e) {
            if (!(e instanceof Error))
              e = new Error(e);
            return {ok: false, message: e.message, name: e.name, stack: e.stack};
          }
          if (Object.prototype.toString.call(value) == '[object Generator]') {
            let generator = value.next();
            if (!generator.done) {
              let id = next_generator_id++;
              generator.id = id;
              generators.set(id, value);
            }
            return {ok: true, generator};
          }
          return {ok: true, value};
        }

        globalThis.__wasmjs = {
          eval(expr) {
            return JSON.stringify(wrap(eval, expr));
          },
          generator_next(id, value) {
            let data = wrap(() => generators.get(id).next(value));
            if (!data.ok || data.value.done)
              generators.delete(id);
            return JSON.stringify(data);
          }
        };
      }
    """

    def eval(self, expr):
        """Evaluate `expr` as a JavaScript expression."""

        data = self._eval(f'__wasmjs.eval({_json_dumps(expr)})')
        if (generator := data.get('generator')):
            return self._run_generator(generator)
        return data.get('value')

    def _eval(self, expr):
        try:
            with self._inst.api.js.eval_to_jsval(expr) as jsval:
                data = json.loads(jsval.to_string())
        except wasmfile.wasmtime.Trap as e:
            raise InterpreterError() from e
        if not data['ok']:
            data.pop('ok')
            raise JSError(**data)
        return data

    def _run_generator(self, generator):
        genid = generator.get('id')
        while True:
            if generator['done']:
                return generator.get('value')
            incoming = yield generator['value']
            generator = self._eval(
                f'__wasmjs.generator_next({genid}, {_json_dumps(incoming)})')['value']


class JSError(Exception):
    """Any exception generated by the QuickJS runtime."""

    def __init__(self, *, name, message, stack=None):
        self.name = name
        self.message = message
        self.stack = stack
        super().__init__(f'{name}: {message}')


class InterpreterError(Exception):
    """Any exception generated by the Wasmtime runtime."""


def _json_dumps(val):
    return json.dumps(val, separators=(',', ':'))
