"""Simple wrapper around QuickJS-NG's qjs-wasi-reactor.wasm."""

import contextlib
import importlib.resources
import json

from wasmjs import lifecycle
from wasmjs import wasmfile

_BOOTSTRAP = """
globalThis.__eval_json = function(src) {
  try {
    return JSON.stringify({ok: true, value: eval(src)});
  } catch (e) {
    return JSON.stringify({ok: false, error: String(e)});
  }
};
"""


class WasmJS:
    """Simple wrapper around QuickJS-NG's qjs-wasi-reactor.wasm."""

    _wasmfile = None

    def __init__(self):
        if not self._wasmfile:
            WasmJS._wasmfile = wasmfile.WasmFile(wasm=importlib.resources.files(
                'qjs-wasi-reactor').joinpath('qjs-wasi-reactor.wasm').read_bytes())

        self._inst = self._wasmfile.instantiate()
        assert self._inst.exports.memory.pointer_size == 4, (
            'This build of wasmjs assumes JSValues are NaN-boxed int64s.')
        self._inst.exports.qjs_init()
        self._api = _PythonicAPI(self._inst)

        with self._api.eval_to_jsval(_BOOTSTRAP):
            pass

    def eval(self, s):
        """Evaluate s as a JavaScript expression."""

        with self._api.eval_to_jsval(f'__eval_json({json.dumps(s)})') as jsval:
            data = json.loads(jsval.to_string())
        if not data['ok']:
            raise JSError(data['error'])
        return data.get('value')


class JSError(Exception):
    """Any exception generated by the QuickJS runtime."""


class _PythonicAPI:

    def __init__(self, inst):
        self.inst = inst
        self.lowlevel = _CAPI(inst)

    def call_to_jsval(self, func_nanbox, *args, this_nanbox=0):
        """Return func_nanbox.call(this_nanbox, *args) as a JSValue."""

        with contextlib.ExitStack() as stack:
            jsval_nanboxes = []
            for arg in args:
                with self.inst.write_string(arg) as written:
                    jsval_nanbox = self.lowlevel.NewStringLen(written.offset, written.size - 1)
                jsval_nanboxes.append(jsval_nanbox.to_bytes(8, 'little', signed=True))
                stack.enter_context(_JSValue(api=self, nanbox=jsval_nanbox))
            with self.inst.write_buf(b''.join(jsval_nanboxes)) as written_argv:
                jsval_nanbox = self.lowlevel.Call(func_nanbox, this_nanbox, len(args),
                                                  written_argv.offset)
        return _JSValue(api=self, nanbox=jsval_nanbox)

    def eval_to_jsval(self, s):
        """Return eval(s) as a JSValue."""

        with self.inst.write_string(s) as written:
            jsval_nanbox = self.lowlevel.Eval(written.offset, written.size - 1, 0, 0)
        return _JSValue(api=self, nanbox=jsval_nanbox)

    def jsval_to_cstr(self, jsval_nanbox):
        """Return String(JSValue) as a C string."""

        with self.inst.reserve_size_t() as sizet:
            cstr_offset = self.lowlevel.ToCStringLen2(sizet.offset, jsval_nanbox, 0)
            return _CString(api=self, offset=cstr_offset, utf8_len=sizet.to_int())


class _CString(lifecycle.PythonOwnedObject):

    def to_string(self):
        """Convert this C string to a Python string."""

        return self.api.inst.exports.memory.read(self.offset,
                                                 self.offset + self.utf8_len).decode('utf-8')

    def close(self):
        self.api.lowlevel.FreeCString(self.offset)


class _JSValue(lifecycle.PythonOwnedObject):

    def to_string(self):
        """Convert this JSValue to a Python string."""

        with self.api.jsval_to_cstr(self.nanbox) as cstr:
            return cstr.to_string()

    @property
    def tag(self):
        """Essentially the type of data represented by the JSValue."""

        return self.nanbox >> 32

    @property
    def stored_value(self):
        """Typically either a linear memory offset or a [small] literal value."""

        return self.nanbox & ((1 << 32) - 1)

    def close(self):
        self.api.lowlevel.FreeValue(self.nanbox)


class _CAPI:  # pylint: disable=invalid-name,missing-function-docstring
    """See https://github.com/quickjs-ng/quickjs/blob/master/quickjs.h."""

    def __init__(self, inst):
        self.inst = inst
        self.ctx = inst.exports.qjs_get_context()

    def Call(self, func_nanbox, this_nanbox, argc, argv_offset):
        return self.inst.exports.JS_Call(self.ctx, func_nanbox, this_nanbox, argc, argv_offset)

    def Eval(self, input_offset, input_len, filename_offset, eval_flags):
        return self.inst.exports.JS_Eval(self.ctx, input_offset, input_len, filename_offset,
                                         eval_flags)

    def FreeCString(self, cstr_offset):
        return self.inst.exports.JS_FreeCString(self.ctx, cstr_offset)

    def FreeValue(self, jsval_nanbox):
        return self.inst.exports.JS_FreeValue(self.ctx, jsval_nanbox)

    def NewStringLen(self, str1_offset, len1):
        return self.inst.exports.JS_NewStringLen(self.ctx, str1_offset, len1)

    def ToCStringLen2(self, sizet_offset, jsvalue_nanbox, cesu8):
        return self.inst.exports.JS_ToCStringLen2(self.ctx, sizet_offset, jsvalue_nanbox, cesu8)
