"""Simple wrapper around QuickJS-NG's qjs-wasi-reactor.wasm."""

import contextlib
import importlib.resources
import json

from wasmjs import jsvalueutil
from wasmjs import wasmfile


class WasmJS:
    """Simple wrapper around QuickJS-NG's qjs-wasi-reactor.wasm."""

    _wasmfile = None

    def __init__(self):
        if not self._wasmfile:
            WasmJS._wasmfile = wasmfile.WasmFile(wasm=importlib.resources.files(
                'qjs-wasi-reactor').joinpath('qjs-wasi-reactor.wasm').read_bytes())

        self._inst = self._wasmfile.instantiate()
        assert self._inst.exports.memory.pointer_size == 4, (
            'This build of wasmjs assumes JSValues are NaN-boxed int64s.')
        self._inst.exports.qjs_init()
        self._api = _PythonicAPI(self._inst)

        if self._bootstrap:
            with self._api.eval_to_jsval(self._bootstrap):
                pass

    _bootstrap = """
        globalThis.__wej = function wasmjs_eval(src) {
          try {
            return JSON.stringify({ok: true, value: eval(src)});
          } catch (e) {
            if (!(e instanceof Error))
              e = new Error(e);
            return JSON.stringify({ok: false, message: e.message, name: e.name, stack: e.stack});
          }
        };
    """

    def eval(self, expr):
        """Evaluate s as a JavaScript expression."""

        with self._api.eval_to_jsval(f'__wej({json.dumps(expr)})') as jsval:
            data = json.loads(jsval.to_string())
        if not data['ok']:
            data.pop('ok')
            raise JSError(**data)
        return data.get('value')


class JSError(Exception):
    """Any exception generated by the QuickJS runtime."""

    def __init__(self, *, name, message, stack=None):
        self.name = name
        self.message = message
        self.stack = stack
        super().__init__(f'{name}: {message}')


class _PythonicAPI:

    def __init__(self, inst):
        self.inst = inst
        self.lowlevel = _CAPI(inst)

    def call_to_jsval(self, func_nanbox, *args, this_nanbox=0):
        """Return func_nanbox.call(this_nanbox, *args) as a JSValue."""

        with contextlib.ExitStack() as stack:
            jsval_nanboxes = []
            for arg in args:
                jsval = stack.enter_context(jsvalueutil.JSValue.encode(self, arg))
                jsval_nanboxes.append(jsval.nanbox.to_bytes(8, 'little', signed=True))
            with self.inst.write_buf(b''.join(jsval_nanboxes)) as written_argv:
                jsval_nanbox = self.lowlevel.Call(func_nanbox, this_nanbox, len(args),
                                                  written_argv.offset)
        return jsvalueutil.JSValue(api=self, nanbox=jsval_nanbox)

    def eval_to_jsval(self, s):
        """Return eval(s) as a JSValue."""

        with self.inst.write_string(s) as written:
            jsval_nanbox = self.lowlevel.Eval(written.offset, written.size - 1, 0, 0)
        return jsvalueutil.JSValue(api=self, nanbox=jsval_nanbox)


class _CAPI:  # pylint: disable=invalid-name,missing-function-docstring
    """See https://github.com/quickjs-ng/quickjs/blob/master/quickjs.h."""

    def __init__(self, inst):
        self.inst = inst
        self.ctx = inst.exports.qjs_get_context()

    def Call(self, func_nanbox, this_nanbox, argc, argv_offset):
        return self.inst.exports.JS_Call(self.ctx, func_nanbox, this_nanbox, argc, argv_offset)

    def Eval(self, input_offset, input_len, filename_offset, eval_flags):
        return self.inst.exports.JS_Eval(self.ctx, input_offset, input_len, filename_offset,
                                         eval_flags)

    def FreeCString(self, cstr_offset):
        return self.inst.exports.JS_FreeCString(self.ctx, cstr_offset)

    def FreeValue(self, jsval_nanbox):
        return self.inst.exports.JS_FreeValue(self.ctx, jsval_nanbox)

    def JSONStringify(self, obj_nanbox, replacer_nanbox, space0_nanbox):
        return self.inst.exports.JS_JSONStringify(self.ctx, obj_nanbox, replacer_nanbox,
                                                  space0_nanbox)

    def NewStringLen(self, str1_offset, len1):
        return self.inst.exports.JS_NewStringLen(self.ctx, str1_offset, len1)

    def ToCStringLen2(self, sizet_offset, jsvalue_nanbox, cesu8):
        return self.inst.exports.JS_ToCStringLen2(self.ctx, sizet_offset, jsvalue_nanbox, cesu8)
